import { StyleSheet } from 'react-native';

export default css = StyleSheet.create({
  modalContainer: {
    flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalCloseArea: {
    flex: 1,
    width: '100%',
    height: '40%',
    opacity: 0,
    pointerEvents: 'auto',
  },
  title: {
    width: '97%',
    fontSize: 20,
    padding: 10,
    color: "#fff",
    fontWeight: "700",
    backgroundColor: '#7EB3FA',
    textAlign: "center",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalContent: {
    width: '97%',
    backgroundColor: '#7EB3FA',
    alignItems: "center",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  label: {
    width: '95%',
    fontSize: 16,
    color: '#fff',
    marginBottom: 5,
    textAlign: 'left',
    paddingLeft: 1,
  },
  input: {
    width: '95%',
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 15,
    paddingLeft: 10,
    backgroundColor: '#fff',
  },
  select: {
    width: '95%',
    height: 47,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 10, // Bordas arredondadas
    marginBottom: 15,
    paddingLeft: 10,
    backgroundColor: '#fff',
  },
  inputDate: {
    width: 100, 
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 15,
    paddingLeft: 10,
    backgroundColor: '#fff',
    paddingRight: 10,
  },
  inputShort: {
    width: 100, 
    height: 48,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 15,
    paddingLeft: 10,
    backgroundColor: '#fff',
    textAlign: 'center',
  },
  inputArea:{
    width: '97%',
    paddingLeft: 3,
  },
  addButton: {
    width: '97%',
    backgroundColor: '#1B61BC',
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 30,
  },
  addButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
